export const pdfTools = [
  { id: 'merge-pdf', path: '/merge-pdf', title: 'Merge PDF', description: 'Combine PDF files in the order you choose.', icon: '↘', operation: 'merge', multiple: true, accepts: ['application/pdf'], controls: 'files', intro: 'Join several PDF documents into one file. Select at least two PDFs and arrange them in the desired order before merging.' },
  { id: 'split-pdf', path: '/split-pdf', title: 'Split PDF', description: 'Extract pages from a PDF into a new file.', icon: '↗', operation: 'split', accepts: ['application/pdf'], controls: 'pages', intro: 'Choose page numbers or ranges to create a separate PDF containing only the pages you need.' },
  { id: 'organize-pdf', path: '/organize-pdf', title: 'Organize PDF', description: 'Reorder PDF pages into a new sequence.', icon: '⇅', operation: 'organize', accepts: ['application/pdf'], controls: 'pages', intro: 'Rearrange every page by entering the page sequence you want, such as 3,1,2. Include each page exactly once.' },
  { id: 'compress-pdf', path: '/compress-pdf', title: 'Optimize PDF', description: 'Re-save a PDF with compressed object streams.', icon: '⌗', operation: 'compress', accepts: ['application/pdf'], controls: 'none', intro: 'Re-save the document using compressed PDF object streams. Results vary by document and may not reduce image-heavy files.' },
  { id: 'rotate-pdf', path: '/rotate-pdf', title: 'Rotate PDF', description: 'Rotate every page by 90, 180, or 270 degrees.', icon: '⟳', operation: 'rotate', accepts: ['application/pdf'], controls: 'rotation', intro: 'Rotate the pages in your PDF by a quarter turn, half turn, or three-quarter turn and download a new copy.' },
  { id: 'watermark-pdf', path: '/watermark-pdf', title: 'Watermark PDF', description: 'Stamp a text watermark across every page.', icon: '▤', operation: 'watermark', accepts: ['application/pdf'], controls: 'watermark', intro: 'Add a light, diagonal text watermark to every page. Your original document is not changed.' },
  { id: 'page-numbers-pdf', path: '/page-numbers-pdf', title: 'Page numbers', description: 'Add page numbers to the bottom of each page.', icon: '1 2', operation: 'page-numbers', accepts: ['application/pdf'], controls: 'none', intro: 'Add centered page numbers to each page in a new copy of your PDF.' },
  { id: 'image-to-pdf', path: '/image-to-pdf', title: 'Image to PDF', description: 'Place JPG or PNG images into a PDF document.', icon: 'JPG', operation: 'image-to-pdf', multiple: true, accepts: ['image/jpeg', 'image/png'], controls: 'files', intro: 'Turn one or more JPG or PNG images into a PDF. Each image is placed on its own page at its original dimensions.' },
  { id: 'pdf-to-jpg', path: '/pdf-to-jpg', title: 'PDF to JPG', description: 'Render each PDF page as a JPG image.', icon: 'JPG', operation: 'pdf-to-jpg', accepts: ['application/pdf'], controls: 'none', clientOnly: true, intro: 'Render PDF pages as JPG files directly in your browser. The images are bundled in a ZIP download; the PDF is not uploaded to MyPDF.' },
  { id: 'crop-pdf', path: '/crop-pdf', title: 'Crop PDF', description: 'Set a visible crop area on every PDF page.', icon: '⌗', operation: 'crop', accepts: ['application/pdf'], controls: 'crop', intro: 'Set the visible crop area on every page using percentages. Cropping changes the page view box; it does not permanently remove hidden content.' },
  { id: 'sign-pdf', path: '/sign-pdf', title: 'Sign PDF', description: 'Add typed signature text to the final page.', icon: '✎', operation: 'sign', accepts: ['application/pdf'], controls: 'signature', intro: 'Add a typed name to the final page as a simple signature mark. This is not a certificate-backed digital signature.' },
];
